# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00b03ae6ddd8abdcd3fe690d3cae73a261eb11e0b63a348439d328d3c83cb111b4ceca6634b5bdda3db5a140fb6f442c25e5fa53f3ec6f65e496569ae30bff5b

test:
  secret_key_base: bb2a005dc8f241a1d4abb0965d0799b4f8e4f54924781997234846b397c9e4e9c3c2fbd49978e454d3b0f62710bb3035fbf2caeaac525cdebf5c2fff1980ae68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
